/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CBM_H_
#define	_CBM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "CollectiveBehaviour.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CBM */
typedef struct CBM {
	ItsPduHeader_t	 header;
	CollectiveBehaviour_t	 cbm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CBM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CBM;

#ifdef __cplusplus
}
#endif

#endif	/* _CBM_H_ */
#include "asn_internal.h"
