/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CollectiveBehaviour_H_
#define	_CollectiveBehaviour_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GenerationDeltaTime.h"
#include "CbmParameters.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CollectiveBehaviour */
typedef struct CollectiveBehaviour {
	GenerationDeltaTime_t	 generationDeltaTime;
	CbmParameters_t	 cbmParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CollectiveBehaviour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CollectiveBehaviour;
extern asn_SEQUENCE_specifics_t asn_SPC_CollectiveBehaviour_specs_1;
extern asn_TYPE_member_t asn_MBR_CollectiveBehaviour_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CollectiveBehaviour_H_ */
#include "asn_internal.h"
