/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_MemberVehicles_H_
#define	_MemberVehicles_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vehicle;

/* MemberVehicles */
typedef struct MemberVehicles {
	A_SEQUENCE_OF(struct Vehicle) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MemberVehicles_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MemberVehicles;
extern asn_SET_OF_specifics_t asn_SPC_MemberVehicles_specs_1;
extern asn_TYPE_member_t asn_MBR_MemberVehicles_1[1];
extern asn_per_constraints_t asn_PER_type_MemberVehicles_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MemberVehicles_H_ */
#include "asn_internal.h"
