/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_MergeContainer_H_
#define	_MergeContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PlatoonID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MergeContainer */
typedef struct MergeContainer {
	PlatoonID_t	 fix;
	PlatoonID_t	 join;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MergeContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MergeContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_MergeContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_MergeContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MergeContainer_H_ */
#include "asn_internal.h"
