/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PlatoonID_H_
#define	_PlatoonID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PlatoonID */
typedef unsigned long	 PlatoonID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PlatoonID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PlatoonID;
extern const asn_INTEGER_specifics_t asn_SPC_PlatoonID_specs_1;
asn_struct_free_f PlatoonID_free;
asn_struct_print_f PlatoonID_print;
asn_constr_check_f PlatoonID_constraint;
ber_type_decoder_f PlatoonID_decode_ber;
der_type_encoder_f PlatoonID_encode_der;
xer_type_decoder_f PlatoonID_decode_xer;
xer_type_encoder_f PlatoonID_encode_xer;
oer_type_decoder_f PlatoonID_decode_oer;
oer_type_encoder_f PlatoonID_encode_oer;
per_type_decoder_f PlatoonID_decode_uper;
per_type_encoder_f PlatoonID_encode_uper;
per_type_decoder_f PlatoonID_decode_aper;
per_type_encoder_f PlatoonID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PlatoonID_H_ */
#include "asn_internal.h"
