/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PlatoonContainer_H_
#define	_PlatoonContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SplitContainer.h"
#include "MergeContainer.h"
#include "StatusContainer.h"
#include "UpdateContainer.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PlatoonContainer_PR {
	PlatoonContainer_PR_NOTHING,	/* No components present */
	PlatoonContainer_PR_splitContainer,
	PlatoonContainer_PR_mergeContainer,
	PlatoonContainer_PR_statusContainer,
	PlatoonContainer_PR_updateContainer
	/* Extensions may appear below */
	
} PlatoonContainer_PR;

/* PlatoonContainer */
typedef struct PlatoonContainer {
	PlatoonContainer_PR present;
	union PlatoonContainer_u {
		SplitContainer_t	 splitContainer;
		MergeContainer_t	 mergeContainer;
		StatusContainer_t	 statusContainer;
		UpdateContainer_t	 updateContainer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PlatoonContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PlatoonContainer;
extern asn_CHOICE_specifics_t asn_SPC_PlatoonContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_PlatoonContainer_1[4];
extern asn_per_constraints_t asn_PER_type_PlatoonContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PlatoonContainer_H_ */
#include "asn_internal.h"
