/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ReformType_H_
#define	_ReformType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReformType {
	ReformType_split	= 0,
	ReformType_merge	= 1
} e_ReformType;

/* ReformType */
typedef long	 ReformType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReformType;
asn_struct_free_f ReformType_free;
asn_struct_print_f ReformType_print;
asn_constr_check_f ReformType_constraint;
ber_type_decoder_f ReformType_decode_ber;
der_type_encoder_f ReformType_encode_der;
xer_type_decoder_f ReformType_decode_xer;
xer_type_encoder_f ReformType_encode_xer;
oer_type_decoder_f ReformType_decode_oer;
oer_type_encoder_f ReformType_encode_oer;
per_type_decoder_f ReformType_decode_uper;
per_type_encoder_f ReformType_encode_uper;
per_type_decoder_f ReformType_decode_aper;
per_type_encoder_f ReformType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReformType_H_ */
#include "asn_internal.h"
