/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SimpleBaseContainer_H_
#define	_SimpleBaseContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MemberStationIDs;

/* SimpleBaseContainer */
typedef struct SimpleBaseContainer {
	StationID_t	 lead;
	struct MemberStationIDs	*members;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SimpleBaseContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleBaseContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SimpleBaseContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SimpleBaseContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleBaseContainer_H_ */
#include "asn_internal.h"
