/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#include "SimpleBaseContainer.h"

#include "MemberStationIDs.h"
asn_TYPE_member_t asn_MBR_SimpleBaseContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SimpleBaseContainer, lead),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"lead"
		},
	{ ATF_POINTER, 1, offsetof(struct SimpleBaseContainer, members),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MemberStationIDs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"members"
		},
};
static const int asn_MAP_SimpleBaseContainer_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_SimpleBaseContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SimpleBaseContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lead */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* members */
};
asn_SEQUENCE_specifics_t asn_SPC_SimpleBaseContainer_specs_1 = {
	sizeof(struct SimpleBaseContainer),
	offsetof(struct SimpleBaseContainer, _asn_ctx),
	asn_MAP_SimpleBaseContainer_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_SimpleBaseContainer_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SimpleBaseContainer = {
	"SimpleBaseContainer",
	"SimpleBaseContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_SimpleBaseContainer_tags_1,
	sizeof(asn_DEF_SimpleBaseContainer_tags_1)
		/sizeof(asn_DEF_SimpleBaseContainer_tags_1[0]), /* 1 */
	asn_DEF_SimpleBaseContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_SimpleBaseContainer_tags_1)
		/sizeof(asn_DEF_SimpleBaseContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SimpleBaseContainer_1,
	2,	/* Elements count */
	&asn_SPC_SimpleBaseContainer_specs_1	/* Additional specs */
};

