/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SplitContainer_H_
#define	_SplitContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PlatoonID.h"
#include "SimpleBaseContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ItineraryPath;

/* SplitContainer */
typedef struct SplitContainer {
	PlatoonID_t	 platoon;
	SimpleBaseContainer_t	 s1;
	struct ItineraryPath	*itinerary1;	/* OPTIONAL */
	SimpleBaseContainer_t	 s2;
	struct ItineraryPath	*itinerary2;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SplitContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SplitContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SplitContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SplitContainer_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SplitContainer_H_ */
#include "asn_internal.h"
