/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Type_H_
#define	_Type_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Type {
	Type_reform	= 0,
	Type_status	= 2,
	Type_update	= 3
} e_Type;

/* Type */
typedef long	 Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Type;
asn_struct_free_f Type_free;
asn_struct_print_f Type_print;
asn_constr_check_f Type_constraint;
ber_type_decoder_f Type_decode_ber;
der_type_encoder_f Type_encode_der;
xer_type_decoder_f Type_decode_xer;
xer_type_encoder_f Type_encode_xer;
oer_type_decoder_f Type_decode_oer;
oer_type_encoder_f Type_encode_oer;
per_type_decoder_f Type_decode_uper;
per_type_encoder_f Type_encode_uper;
per_type_decoder_f Type_decode_aper;
per_type_encoder_f Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Type_H_ */
#include "asn_internal.h"
