/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CBM-PDU-Descriptions"
 * 	found in "asn1/VeNIT-v100-CBM.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Vehicle_H_
#define	_Vehicle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReferencePosition;

/* Vehicle */
typedef struct Vehicle {
	StationID_t	 stationID;
	struct ReferencePosition	*referencePosition;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vehicle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vehicle;
extern asn_SEQUENCE_specifics_t asn_SPC_Vehicle_specs_1;
extern asn_TYPE_member_t asn_MBR_Vehicle_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Vehicle_H_ */
#include "asn_internal.h"
