name: check 32-bit compatibility
on:
  push:
    branches:
      - master
jobs:
  docker-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: linux/386
            tag: x86
          - docker: linux/arm/v7
            tag: armv7
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: >
          docker build
          --platform ${{matrix.platform.name}}
          --build-arg UBUNTU_VERSION=bionic
          --tag vanetza/docker:${{matrix.platform.tag}}
          ${{github.workspace}}/tools/docker
      - run: >
          docker run --rm
          --platform ${{matrix.platform.name}}
          -v${{github.workspace}}:/home/build-user/workspace:ro
          vanetza/docker:${{matrix.platform.tag}}
